YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Constants (CPL Error Codes)",
        "Constants (CPL Error Levels)",
        "Constants (DCAP)",
        "Constants (DMD)",
        "Constants (GCI)",
        "Constants (GDT)",
        "Constants (GRA)",
        "Constants (ODsC)",
        "Constants (OFT)",
        "Constants (OJ)",
        "Constants (OLC)",
        "Constants (wkbByteOrder)",
        "Constants (wkbGeometryType)",
        "Constants (wkbVariant)",
        "gdal",
        "gdal.CoordinateTransformation",
        "gdal.Dataset",
        "gdal.DatasetBands",
        "gdal.DatasetLayers",
        "gdal.Driver",
        "gdal.Envelope",
        "gdal.Envelope3D",
        "gdal.Feature",
        "gdal.FeatureDefn",
        "gdal.FeatureDefnFields",
        "gdal.FeatureFields",
        "gdal.FieldDefn",
        "gdal.GDALDrivers",
        "gdal.Geometry",
        "gdal.GeometryCollection",
        "gdal.GeometryCollectionChildren",
        "gdal.Layer",
        "gdal.LayerFeatures",
        "gdal.LayerFields",
        "gdal.LineString",
        "gdal.LineStringPoints",
        "gdal.LinearRing",
        "gdal.MultiLineString",
        "gdal.MultiPoint",
        "gdal.MultiPolygon",
        "gdal.Point",
        "gdal.Polygon",
        "gdal.PolygonRings",
        "gdal.RasterBand",
        "gdal.RasterBandOverviews",
        "gdal.RasterBandPixels",
        "gdal.SpatialReference"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});